### ISSUE TITLE
'make html' not generating sphinx documentation

### ISSUE THREAD

**Issue by jkhani** [raspearsy/bme590hrm#31]
I am receiving the following error when attempting to run the command 'make html' from the terminal: 

bash: make: command not found.

I have completed the following steps:
- run sphinx-quickstart
- create docs/ subdirectory
- selected 'y' for autodoc
- uncommented sys.path.insert(0, os.path.abspath('..')) in conf.py
- run sphinx-apidoc -o doc . and generated the .rst files for all the .py modules
- add modules ot index.rst to be included in documentation

**Comment by jkhani** [comment]
It seems like the same sequence of steps works on Nisarg's machine, but not mine..

**Comment by mlp6** [comment]
Hmmmm... That is strange.  Same local Python configs?

**Comment by nisargmshah** [comment]
I think Josh is using Git Bash and maybe that command doesn't work there. I got those steps to work through Anaconda Prompt. I don't think you need to worry about it Josh, the documentation is up on the develop_io branch right now, and Ryan was able to pull and view the html on his computer as well.
