### ISSUE TITLE
add averaging period attribute

### ISSUE THREAD

**Issue by raspearsy** [raspearsy/bme590hrm#35]
This attribute is acquired in input and passed to 

Changes needed in input to acquire this attribute
Changes needed in ecg_measure to set attribute from input to attribute native to ecg_measure

**Comment by gaa37** [comment]
Left as a commented attribute for now that will be pulled from ECGInput Class 
# self.averagingPeriod = inputfile.averagingPeriod

**Comment by jkhani** [comment]
Added the averaging_period as an attribute of the ECGMeasure class object with ecgmeasure.py
