### ISSUE TITLE
Inputting the CSV File

### ISSUE THREAD

**Issue by nisargmshah** [raspearsy/bme590hrm#7]
When reading in the CSV file, is it safe to assume that the first column is time and the second column is the lead voltage?

**Comment by mlp6** [comment]
Yes; sorry if that wasn't clear from the assignment handout.  Time will be in seconds; voltage in millivolts.

**Comment by nisargmshah** [comment]
Alright, thank you. I just wanted to make sure that the order of the columns would not be switched.
